class TimedTextCircuitBreaker {
  constructor({ threshold = Number(process.env.TIMED_TEXT_429_THRESHOLD) || 2,
    cooldownMs = Number(process.env.TIMED_TEXT_COOLDOWN_MS) || 15 * 60 * 1000, now = Date.now } = {}) {
    this.threshold = threshold; this.cooldownMs = cooldownMs; this.now = now; this.consecutive429 = 0; this.openedAt = null;
  }
  shouldSkipDirect() {
    if (this.openedAt === null) return false;
    if (this.now() - this.openedAt < this.cooldownMs) return true;
    this.openedAt = null; this.consecutive429 = 0; return false;
  }
  recordSuccess() { this.consecutive429 = 0; this.openedAt = null; }
  recordFailure(error) {
    if (error?.httpStatus === 429) {
      this.consecutive429++;
      if (this.consecutive429 >= this.threshold) this.openedAt = this.now();
    } else this.consecutive429 = 0;
  }
  state() { return { consecutive429: this.consecutive429, openedAt: this.openedAt, cooldownMs: this.cooldownMs }; }
}

class TranscriptProviderChain {
  constructor({ fetchDirect, extensionProvider, circuitBreaker = new TimedTextCircuitBreaker(), logger = () => {} } = {}) {
    this.fetchDirect = fetchDirect; this.extensionProvider = extensionProvider; this.circuitBreaker = circuitBreaker; this.logger = logger;
    this.metrics = { directCaptionAttempts: 0, directCaptionSuccess: 0, directCaption429: 0,
      extensionAttempts: 0, extensionSuccess: 0, extensionFailures: 0, extensionMs: 0 };
  }
  async getTranscript({ track, metadata, signal, jobId = null, onProviderAttempt = () => {} }) {
    const failures = [];
    const metrics = { directCaptionAttempts: 0, directCaptionSuccess: 0, directCaption429: 0, directCaptionMs: 0,
      extensionAttempts: 0, extensionSuccess: 0, extensionFailures: 0, extensionMs: 0 };
    if (!this.circuitBreaker.shouldSkipDirect()) {
      onProviderAttempt('DIRECT_CAPTION'); this.metrics.directCaptionAttempts++; metrics.directCaptionAttempts++;
      const directStarted = Date.now(); this.logger({ event: 'provider-start', jobId, videoId: metadata.videoId, provider: 'DIRECT_CAPTION' });
      try {
        const transcriptCues = await this.fetchDirect(track, signal);
        metrics.directCaptionMs = Date.now() - directStarted;
        this.metrics.directCaptionSuccess++; metrics.directCaptionSuccess++; this.circuitBreaker.recordSuccess();
        this.logger({ event: 'provider-success', jobId, videoId: metadata.videoId, provider: 'DIRECT_CAPTION', duration: Date.now() - directStarted });
        return { transcriptCues, transcriptLanguage: track.language, transcriptSource: track.source,
          transcriptProvider: { provider: 'DIRECT_CAPTION', language: track.language,
            isAutoGenerated: track.source === 'automatic', retrievedAt: new Date().toISOString() }, transcriptMetrics: metrics };
      } catch (error) {
        metrics.directCaptionMs = Date.now() - directStarted;
        this.logger({ event: 'provider-failure', jobId, videoId: metadata.videoId, provider: 'DIRECT_CAPTION', errorCode: error.code, duration: Date.now() - directStarted });
        failures.push({ provider: 'DIRECT_CAPTION', code: error.code, status: error.httpStatus });
        this.circuitBreaker.recordFailure(error); if (error.httpStatus === 429) { this.metrics.directCaption429++; metrics.directCaption429++; }
        if (!error.retryableTranscriptTransport) throw error;
      }
    }
    onProviderAttempt('EMBEDDED_EXTENSION'); this.metrics.extensionAttempts++; metrics.extensionAttempts++;
    const started = Date.now();
    this.logger({ event: 'provider-start', jobId, videoId: metadata.videoId, provider: 'EMBEDDED_EXTENSION' });
    try {
      const result = await this.extensionProvider.extract({ videoId: metadata.videoId, url: metadata.url, durationSeconds: metadata.durationSeconds, signal });
      const elapsed = Date.now() - started;
      this.metrics.extensionSuccess++; metrics.extensionSuccess++; this.metrics.extensionMs += elapsed; metrics.extensionMs = elapsed;
      this.logger({ event: 'provider-success', jobId, videoId: metadata.videoId, provider: 'EMBEDDED_EXTENSION', duration: elapsed });
      return { ...result, transcriptMetrics: metrics };
    } catch (error) {
      if (error.code === 'ANALYSIS_CANCELLED') throw error;
      this.metrics.extensionFailures++; metrics.extensionFailures++; failures.push({ provider: 'EMBEDDED_EXTENSION', code: error.code || 'EXTENSION_TRANSCRIPT_UNAVAILABLE' });
      const exhausted = Object.assign(new Error(`Transcript providers exhausted: ${failures.map(item => `${item.provider}:${item.code}`).join(', ')}`),
        { code: 'TRANSCRIPT_PROVIDERS_EXHAUSTED', providerFailures: failures });
      this.logger({ event: 'provider-failure', jobId, videoId: metadata.videoId, provider: 'EMBEDDED_EXTENSION', errorCode: error.code, duration: Date.now() - started });
      throw exhausted;
    }
  }
}

module.exports = { TimedTextCircuitBreaker, TranscriptProviderChain };
